---
- hosts: gluster_servers
  remote_user: user
  tasks:
    - name: Copy bup.sh to /scripts
      copy:
        src=./files/bup.sh
        dest=/scripts/
    - name: Make bup.sh executable through shell.
      shell: chmod +x /scripts/bup.sh
      args:
        warn: false
    - name: Add crontab entry for bup.sh to root's crontab
      cron:
        name="Backup varwwwhtml"
        hour="0"
        minute="0"
        job=/scripts/bup.sh
      run_once: true
    - name: Copy pre-defined NginX config to folder
      copy:
        src=./files/default
        dest=/etc/nginx/sites-available/
        force=yes
    - name: Reload NginX
      service:
        name=nginx
        state=reloaded

