---
- hosts: gluster_servers
  remote_user: user
  tasks:
    - name: Add GlusterFS repo GPO key through shell
      shell: wget -O - http://download.gluster.org/pub/gluster/glusterfs/3.9/rsa.pub | apt-key add -
      args:
        warn: False
    - name: Add GlusterFS repository
      apt_repository:
        repo='deb http://download.gluster.org/pub/gluster/glusterfs/3.9/LATEST/Debian/jessie/apt jessie main'
        state=present
        filename=gluster-fs
    - name: Install GlusterFS
      apt:
        name: glusterfs-*
        state: present
        update_cache: yes
    - name: Ensure GlusterFS service is running
      service:
        name=glusterfs-*
        state=started
    - name: Create GlusterFS bricks
      file:
        path=/srv/glusterfs/brick
        state=directory
    - name: Create GlusterFS volumes
      gluster_volume:
        bricks=/srv/glusterfs/brick
        cluster={{groups.gluster_servers | join(",")}}
        replicas=2
        name=TestBrick
        state=present
        force=true
      run_once: true
    - name: Create GlusterFS brick mount dirs
      file:
        path=/srv/storage/lmao
        state=directory
    - name: Mount
      mount:
        name: /srv/storage/lmao
        src: 192.168.178.22:/TestBrick
        fstype: glusterfs
        opts: "defaults,_netdev"
        state: mounted